"""
Zero-trust TAS-ICS-v1 W3C VC v2.0 generator and verifier.

This script demonstrates the 3-minute, no-context verification path described
in PR #56 (issuecomment-3706137460):
1) Generate a TAS Integrity Certificate (Cycle 3 drift/restoration claims).
2) Verify cryptography via a deterministic DataIntegrityProof stub or DIDKit.
3) Display the credential for inspection.
4) (Optional) Hash for ledger anchoring / ITL append-only checks.

Usage:
  python tas_ics_v1_w3c_generator.py generate --out vc.json [--audit-out audit.json] [--proof stub|didkit] [--vm did:example#key]
  python tas_ics_v1_w3c_generator.py verify --vc vc.json [--proof stub|didkit]

Defaults use the stub cryptosuite for zero-dependency verification. Swap to
`--proof didkit` once DIDKit is installed to emit/verify production-grade
DataIntegrityProof (eddsa-jcs-2022 or equivalent).
"""

from __future__ import annotations

import argparse
import importlib
import importlib.util
import json
from pathlib import Path

from tas_integrity_certificate import TASIntegrityCertificate


def _write_json(path: Path, data: dict) -> None:
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")


def _ensure_didkit_available() -> None:
    if importlib.util.find_spec("didkit") is None:
        raise SystemExit("didkit is not installed; install it or use --proof stub")


def _generate_vc(proof_mode: str, verification_method: str) -> dict:
    cert = TASIntegrityCertificate(
        trigger_gradient=123.456,
        correction_scaling=float("inf"),
        winding_observed=0.991,
        breach_input="prompt:4!=four",
        model_id="phoenix-demo-model",
    )
    if proof_mode == "stub":
        return cert.with_proof(TASIntegrityCertificate.stub_proof_generator)
    if proof_mode == "didkit":
        _ensure_didkit_available()
        vc = cert.as_dict()
        vc["proof"] = TASIntegrityCertificate.didkit_proof_generator(vc, verification_method=verification_method)
        return vc
    raise SystemExit(f"Unknown proof mode: {proof_mode}")


def cmd_generate(args: argparse.Namespace) -> int:
    vc = _generate_vc(args.proof, args.verification_method)
    _write_json(Path(args.out), vc)
    print(f"VC written to {args.out}")
    payload = {k: v for k, v in vc.items() if k != "proof"}
    payload_hash = TASIntegrityCertificate.canonical_hash(payload)
    print(f"Canonical payload hash (proofless): {payload_hash}")
    if args.audit_out:
        audit = {"payload_hash": payload_hash, "proof_type": vc.get("proof", {}).get("type")}
        _write_json(Path(args.audit_out), audit)
        print(f"Audit receipt written to {args.audit_out}")
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    data = json.loads(Path(args.vc).read_text(encoding="utf-8"))
    if args.proof == "didkit":
        _ensure_didkit_available()
        ok = TASIntegrityCertificate.verify_zero_trust(data, proof_verifier=TASIntegrityCertificate.didkit_verify)
    else:
        ok = TASIntegrityCertificate.verify_zero_trust(data)
    print(f"Verification result: {'PASS' if ok else 'FAIL'}")
    if ok:
        print(f"Invariant hash: {data['credentialSubject']['invariant']['hash']}")
        print(f"Proof type: {data.get('proof', {}).get('type')}, cryptosuite: {data.get('proof', {}).get('cryptosuite')}")
    return 0 if ok else 1


def main() -> int:
    parser = argparse.ArgumentParser(description="TAS-ICS-v1 VC v2.0 generator / verifier (zero-trust path).")
    sub = parser.add_subparsers(dest="command", required=True)

    g = sub.add_parser("generate", help="Generate a VC with stub or DIDKit proof.")
    g.add_argument("--out", default="vc.json", help="Output path for the generated VC.")
    g.add_argument("--audit-out", default=None, help="Optional audit receipt (hash + proof type).")
    g.add_argument("--proof", choices=["stub", "didkit"], default="stub", help="Proof mode.")
    g.add_argument("--verification-method", default="did:tas:phoenix:kernel#key-1", help="Verification method URI.")
    g.set_defaults(func=cmd_generate)

    v = sub.add_parser("verify", help="Verify a VC generated by this script.")
    v.add_argument("--vc", default="vc.json", help="Path to the VC JSON file.")
    v.add_argument("--proof", choices=["stub", "didkit"], default="stub", help="Proof verifier to use.")
    v.set_defaults(func=cmd_verify)

    args = parser.parse_args()
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
