import React from 'react';
import { Link } from 'wouter';
import { ShieldCheck, AlertTriangle, BarChart4, Check } from 'lucide-react';
import { useQuery } from '@tanstack/react-query';
import VerificationForm from '@/components/verification-form';

interface SystemStatus {
  status: string;
  version: string;
  components: Record<string, string>;
  lastUpdated: string;
}

function HomePage() {
  // Fetch system status
  const { data: systemStatus, isLoading: systemStatusLoading } = useQuery<SystemStatus>({
    queryKey: ['/api/python-system/status'],
  });

  return (
    <div className="min-h-screen flex flex-col">
      {/* Hero Section */}
      <section className="bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white py-24">
        <div className="container mx-auto px-4">
          <div className="flex flex-col md:flex-row items-center justify-between gap-12">
            <div className="md:w-1/2 space-y-6">
              <div className="inline-block px-3 py-1 bg-white/20 rounded-full text-sm font-medium mb-2">
                Trusted by content teams & publishers worldwide
              </div>
              <h1 className="text-4xl md:text-5xl font-bold leading-tight">
                AI Content Verification that Grows Your Business
              </h1>
              <p className="text-xl">
                Protect your brand from AI hallucinations and false claims. Our verification engine distinguishes between factual content, questions, and potentially fabricated statements.
              </p>
              <div className="flex flex-wrap gap-3">
                <Link href="/pricing" className="bg-white text-purple-700 hover:bg-purple-50 transition-colors px-6 py-3 rounded-lg font-medium">
                  View Pricing
                </Link>
                <Link href="#verify" className="bg-transparent border border-white text-white hover:bg-white/10 transition-colors px-6 py-3 rounded-lg font-medium">
                  Try Demo
                </Link>
              </div>
              <div className="flex items-center text-sm">
                <Check className="text-green-300 h-4 w-4 mr-2" />
                <span>No credit card required for trial</span>
                <span className="mx-2">•</span>
                <Check className="text-green-300 h-4 w-4 mr-2" />
                <span>Enterprise-ready API</span>
                <span className="mx-2">•</span>
                <Check className="text-green-300 h-4 w-4 mr-2" />
                <span>14-day money back</span>
              </div>
            </div>
            <div className="md:w-1/2">
              <div className="relative bg-white/10 backdrop-blur-sm p-6 rounded-xl border border-white/20">
                <div className="absolute -top-3 -right-3 bg-green-500 text-white text-xs px-3 py-1 rounded-full font-medium">
                  System Online
                </div>
                <h3 className="text-xl font-semibold mb-3">System Status</h3>
                {systemStatusLoading ? (
                  <p>Loading system status...</p>
                ) : (
                  <div className="space-y-3">
                    {systemStatus?.components && Object.entries(systemStatus.components).map(([key, value]) => (
                      <div key={key} className="flex items-center gap-2">
                        {value === 'active' ? (
                          <Check className="text-green-400 h-5 w-5" />
                        ) : (
                          <AlertTriangle className="text-amber-400 h-5 w-5" />
                        )}
                        <span className="capitalize">{key.replace(/([A-Z])/g, ' $1').trim()}</span>
                        <span className="text-xs bg-white/20 px-2 py-0.5 rounded ml-auto">
                          {value}
                        </span>
                      </div>
                    ))}
                    <div className="text-xs text-white/70 mt-2">
                      Last Updated: {systemStatus?.lastUpdated && new Date(systemStatus.lastUpdated).toLocaleTimeString()}
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 bg-background">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-12">Key Capabilities</h2>
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-card rounded-xl p-6 shadow-sm border">
              <div className="bg-primary/10 p-3 rounded-lg w-fit mb-4">
                <ShieldCheck className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">AI Fabrication Detection</h3>
              <p className="text-muted-foreground">
                Identify potentially fabricated content generated by AI systems with pattern-based analysis.
              </p>
            </div>
            <div className="bg-card rounded-xl p-6 shadow-sm border">
              <div className="bg-primary/10 p-3 rounded-lg w-fit mb-4">
                <AlertTriangle className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Speculative Content Flagging</h3>
              <p className="text-muted-foreground">
                Highlight speculative claims and statements that lack proper verification or citation.
              </p>
            </div>
            <div className="bg-card rounded-xl p-6 shadow-sm border">
              <div className="bg-primary/10 p-3 rounded-lg w-fit mb-4">
                <BarChart4 className="h-6 w-6 text-primary" />
              </div>
              <h3 className="text-xl font-semibold mb-2">Truth Confidence Scoring</h3>
              <p className="text-muted-foreground">
                Receive detailed confidence scores and analysis of content factuality with visual highlighting.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Verification Section */}
      <section id="verify" className="py-16 bg-gray-50 dark:bg-gray-900/30">
        <div className="container mx-auto px-4">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-3xl font-bold text-center mb-4">Verify Content</h2>
            <p className="text-center text-muted-foreground mb-8">
              Paste any text to verify its factuality using the TrueAlphaSpiral verification engine.
            </p>
            <VerificationForm />
          </div>
        </div>
      </section>

      {/* Testimonials Section */}
      <section className="py-16 bg-background">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-4">Trusted by Content Leaders</h2>
          <p className="text-center text-muted-foreground mb-12 max-w-2xl mx-auto">
            Organizations worldwide rely on TrueAlphaSpiral to ensure content accuracy and protect their brand reputation.
          </p>
          
          <div className="grid md:grid-cols-3 gap-8">
            <div className="bg-card rounded-xl p-6 shadow-sm border">
              <div className="flex items-center space-x-1 mb-4">
                {[1, 2, 3, 4, 5].map((i) => (
                  <svg key={i} className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118l-2.8-2.034c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                ))}
              </div>
              <p className="mb-4 italic">"TrueAlphaSpiral has transformed our content verification process. We now catch questions and speculative content before publishing, which has increased reader trust significantly."</p>
              <div>
                <h4 className="font-semibold">Sarah Johnson</h4>
                <p className="text-sm text-muted-foreground">Content Director, Digital Publishing Inc.</p>
              </div>
            </div>
            
            <div className="bg-card rounded-xl p-6 shadow-sm border">
              <div className="flex items-center space-x-1 mb-4">
                {[1, 2, 3, 4, 5].map((i) => (
                  <svg key={i} className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118l-2.8-2.034c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                ))}
              </div>
              <p className="mb-4 italic">"The API integration was seamless. Our content team now verifies claims in real-time, saving hours of manual fact-checking each day."</p>
              <div>
                <h4 className="font-semibold">Michael Chen</h4>
                <p className="text-sm text-muted-foreground">CTO, TechNews Global</p>
              </div>
            </div>
            
            <div className="bg-card rounded-xl p-6 shadow-sm border">
              <div className="flex items-center space-x-1 mb-4">
                {[1, 2, 3, 4, 5].map((i) => (
                  <svg key={i} className="w-5 h-5 text-yellow-400" fill="currentColor" viewBox="0 0 20 20">
                    <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118l-2.8-2.034c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z" />
                  </svg>
                ))}
              </div>
              <p className="mb-4 italic">"ROI was immediate. The Enterprise plan paid for itself within the first month by preventing a major content accuracy issue that would have damaged our reputation."</p>
              <div>
                <h4 className="font-semibold">Lisa Rodriguez</h4>
                <p className="text-sm text-muted-foreground">VP of Marketing, Enterprise Solutions</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 bg-primary text-primary-foreground">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-3xl font-bold mb-4">Ready to safeguard your content integrity?</h2>
          <p className="max-w-2xl mx-auto mb-8">
            Choose the plan that fits your organization's needs. From small teams to enterprise solutions, 
            we have pricing options that scale with your verification requirements.
          </p>
          <div className="flex gap-4 justify-center flex-wrap">
            <Button variant="outline" asChild>
              <Link href="#verify">Try Demo</Link>
            </Button>
            <Button variant="default" className="bg-white text-primary hover:bg-white/90" asChild>
              <Link href="/pricing">See Pricing Plans</Link>
            </Button>
          </div>
          <p className="mt-6 text-sm max-w-lg mx-auto">
            Join organizations already using TrueAlphaSpiral to verify content and protect their brand reputation
          </p>
        </div>
      </section>
    </div>
  );
}

export default HomePage;

// Button component for the links (since we didn't import the Button component)
function Button({ 
  children, 
  variant = 'default', 
  className = '', 
  asChild = false
}: { 
  children: React.ReactNode; 
  variant?: 'default' | 'outline'; 
  className?: string; 
  asChild?: boolean;
}) {
  const baseStyles = "px-6 py-3 rounded-lg font-medium transition-colors";
  const variantStyles = {
    default: "bg-primary text-primary-foreground hover:bg-primary/90",
    outline: "border border-primary/20 bg-transparent hover:bg-primary/10"
  };
  
  const buttonClassName = `${baseStyles} ${variantStyles[variant]} ${className}`;
  
  return asChild ? (
    <span className={buttonClassName}>{children}</span>
  ) : (
    <button className={buttonClassName}>{children}</button>
  );
}