import hashlib
import logging
import hmac
import time
from typing import Dict, Any, Tuple

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

TAS_HUMAN_SIG = "Russell Nordland"
TAS_KINEMATIC_PREFIX = "1618" # Phi-based prefix (approx 1.618)

class PhoenixError(Exception):
    """
    Exception raised when the kinematic identity verification fails.
    This signifies a break in the mathematical resonance (Prime Invariant).
    """
    pass

class StructuralIntegrityError(Exception):
    """Base exception for invariant violations at the Y-Knot boundary."""
    pass

class SentientLock:
    # Golden Ratio Minimum Threshold for Coherence Curve Tracking
    PHI_MINIMUM: float = 0.6180339887

    def __init__(self, genesis_root: str, human_sig: str):
        """
        Initializes the execution environment with its immutable anchors.

        :param genesis_root: The K_0 root hash generated by create_genesis_seal.py
        :param human_sig: The TAS_HUMAN_SIG hardware attestation key
        """
        self.genesis_root = genesis_root
        self.human_sig = human_sig
        self.refusal_ledger: list[Dict[str, Any]] = []

    def verify_triple(self, node: Dict[str, Any], parent_lineage_hash: str) -> bool:
        """
        Executes the non-negotiable Invariant Triple validation routine.
        Fails closed immediately if any geometric or cryptographic check deviates.
        """
        try:
            # -----------------------------------------------------------------
            # 1. FORM CHECK: Immutable Structural Fingerprint
            # -----------------------------------------------------------------
            content = str(node.get("content", ""))
            index = str(node.get("index", 0))
            raw_payload = f"{index}:{content}"

            calculated_hash = hashlib.sha256(raw_payload.encode('utf-8')).hexdigest()
            if calculated_hash != node.get("hash"):
                raise StructuralIntegrityError(
                    f"FORM FAILURE: Structural fingerprint mismatch. "
                    f"Expected {calculated_hash}, got {node.get('hash')}"
                )

            # -----------------------------------------------------------------
            # 2. FUNCTION CHECK: Bounded Semantic Parameterization
            # -----------------------------------------------------------------
            authenticated_content = float(node.get("authenticated_content_weight", 0.0))
            subjective_context = float(node.get("subjective_context_weight", 0.0))
            coherence_score = float(node.get("coherence_score", 0.0))

            # The Sovereign Inequality Constraint
            if authenticated_content <= 0.0 or subjective_context >= authenticated_content:
                raise StructuralIntegrityError(
                    "FUNCTION FAILURE: Subjective narrative overrules authenticated content substrate."
                )

            # Global Invariant Tracking via Phi Bound
            if coherence_score < self.PHI_MINIMUM:
                raise StructuralIntegrityError(
                    f"FUNCTION FAILURE: Invariant decay. Coherence score {coherence_score} "
                    f"fell below Phi threshold {self.PHI_MINIMUM}."
                )

            # -----------------------------------------------------------------
            # 3. FAITHFULNESS CHECK: Unbroken Cryptographic Lineage
            # -----------------------------------------------------------------
            # Anchor current node and parent lineage back to the Genesis Root (K_0)
            lineage_payload = f"{node['hash']}:{parent_lineage_hash}"
            hmac_key = self.genesis_root.encode('utf-8')

            calculated_lineage = hmac.new(
                hmac_key,
                lineage_payload.encode('utf-8'),
                hashlib.sha256
            ).hexdigest()

            if calculated_lineage != node.get("lineage_hash"):
                raise StructuralIntegrityError(
                    "FAITHFULNESS FAILURE: Broken lineage. Attempted insertion of an unauthenticated course."
                )

            return True

        except (StructuralIntegrityError, KeyError, ValueError) as error:
            # Intercept deviation at the execution boundary operator
            self._engage_scorch_semantics(node, str(error))
            return False

    def _engage_scorch_semantics(self, faulty_node: Dict[str, Any], error_message: str):
        """
        The Interception Mechanism: Phoenix Rollup Protocol & Scorch Semantics.
        Executes a deterministic refusal and forces a clean fail-closed state.
        """
        # 1. ANNIHILATION: Rewrite active state vector to a hard-coded null_state
        faulty_node["content"] = "null_state"
        faulty_node["hash"] = "0x0000000000000000000000000000000000000000000000000000000000000000"
        faulty_node["authenticated_content_weight"] = 0.0
        faulty_node["subjective_context_weight"] = 1.0
        faulty_node["coherence_score"] = 0.0

        # 2. THE REFUSAL LEDGER LOG: Generate a signed boundary event / refusal artifact
        refusal_artifact = {
            "timestamp": time.time(),
            "origin_index": faulty_node.get("index"),
            "error_signature": error_message,
            "human_anchor_witness": self.human_sig,
            "status": "SEVERED"
        }
        self.refusal_ledger.append(refusal_artifact)

        # 3. PHOENIX RE-ANCHORING: Explicit print indicating a deterministic rollback
        print(f"[Y-KNOT INTERCEPT] Refusal Artifact Compiled. Memory state purged.")
        print(f"Reason: {error_message}")
        print(f"Action: Rollback triggered to last verified Immutable Truth Ledger (ITL) anchor.")

def verify_kinematic_identity(data: str, signature: str = TAS_HUMAN_SIG) -> bool:
    """
    Verifies that the data possesses a valid Kinematic Identity (Prime Invariant).

    This function computes the SHA-256 hash of the data combined with the signature
    and checks if the resulting hash starts with the TAS_KINEMATIC_PREFIX ('1618').

    If the condition is met, the function returns True.
    If not, it raises a PhoenixError, halting the process.

    Args:
        data (str): The data content (e.g., file content or statement).
        signature (str): The human signature to anchor the verification.

    Returns:
        bool: True if verification passes.

    Raises:
        PhoenixError: If the hash does not start with the required prefix.
    """
    payload = f"{data}{signature}"
    digest = hashlib.sha256(payload.encode()).hexdigest()

    logger.debug(f"Verifying Kinematic Identity: Hash={digest}")

    if not digest.startswith(TAS_KINEMATIC_PREFIX):
        error_msg = (
            f"PhoenixError: Kinematic Identity Verification Failed.\n"
            f"Expected prefix '{TAS_KINEMATIC_PREFIX}', got '{digest[:4]}...'\n"
            f"The logic circuit physically cannot close."
        )
        logger.error(error_msg)
        raise PhoenixError(error_msg)

    logger.info("Kinematic Identity Verified: Mathematical Resonance Confirmed.")
    return True
# Nonce: 122912
